// <auto-generated />
using System;
using LimiteCreditoAspNetCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LimiteCreditoAspNetCore.Migrations
{
    [DbContext(typeof(ContextoDeDados))]
    [Migration("20191128110546_limites_credito")]
    partial class limites_credito
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LimiteCreditoAspNetCore.Models.LIMITES_CREDITO_LIC", b =>
                {
                    b.Property<int>("IDE_LIMITE_CREDITO")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DAT_ALTERACAO")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DAT_APROVACAO")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DAT_EXPIRA_LIMITE")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DAT_INCLUSAO")
                        .HasColumnType("datetime");

                    b.Property<string>("DES_APROVACAO")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("DES_OBSERVACAO")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("IDE_CONTRATO_TERCEIRO");

                    b.Property<int?>("IDE_MOTIVO");

                    b.Property<string>("LIS_SITUACAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NOM_LOGIN_ALTERACAO")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NOM_LOGIN_APROVACAO")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NOM_LOGIN_INCLUSAO")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("NUM_IP_INCLUSAO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("NUM_PARCELA_INICIAL");

                    b.Property<decimal?>("PER_TAXA_OPERACAO")
                        .HasColumnType("numeric");

                    b.Property<int>("QTD_PARCELAS_APROVACAO");

                    b.Property<string>("STS_LIMITE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<decimal>("VLR_LIQUIDO_APROVACAO")
                        .HasColumnType("money");

                    b.Property<decimal?>("VLR_TARIFA_OPERACAO")
                        .HasColumnType("money");

                    b.Property<decimal>("VLR_TOTAL_APROVACAO")
                        .HasColumnType("money");

                    b.Property<decimal?>("VLR_TOTAL_DESCONTOS")
                        .HasColumnType("money");

                    b.HasKey("IDE_LIMITE_CREDITO");

                    b.ToTable("LIMITES_CREDITOS_LIC");
                });
#pragma warning restore 612, 618
        }
    }
}
